
# azure-pipelines.yml

trigger: none

variables:
  imageName1: 'akkodis-b9gjbfgfdrajfrb6.azurecr.io/oak-ai-autoeval'
  imageName2: 'doesrtsensainprdacr-g9bmdpcfapf5ddgp.azurecr.io/oak-ai-autoeval'
  tag: '$(Build.BuildNumber)'
  gitsha: '$(Build.SourceVersion)'
  acrName: 'akkodis'
  acrName2: 'doesrtsensainprdacr'
  azureSubscription: 'Akkodis SensAI'
  azureSubscription2: 'DOE-ICT-DEVTEST'

stages:
  - stage: BuildAndPushContainer
    displayName: Build and Push Python Tools Docker Image
    jobs:
      - job: Build
        displayName: Build and Push
        pool:
          name: 'ARM64'  # Ensure this matches your Azure DevOps agent pool name
        steps:
          - checkout: self

          - task: DockerInstaller@0
            displayName: Install Docker Buildx
            inputs:
              dockerVersion: '24.0.0'

          - task: AzureCLI@2
            displayName: 'ACR Login, Build, and Push to ACR'
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Login to Azure Container Registry
                az acr login --name $(acrName)

                # Create and use buildx builder for multi-platform builds
                docker buildx create --use || true

                # Build and push multi-platform image (ARM64 + AMD64)
                docker buildx build --platform linux/arm64 \
                  -t $(imageName1):$(tag) \
                  -f Dockerfile \
                  . \
                  --push \
                  --load
                IMAGE_ID=$(docker images --format "{{.ID}}" $(imageName1):$(tag) | head -n 1)
                docker tag $IMAGE_ID $(imageName1):$(gitsha)
                docker tag $IMAGE_ID $(imageName1):latest
                docker tag $IMAGE_ID $(imageName2):$(tag)
                docker tag $IMAGE_ID $(imageName2):$(gitsha)
                docker tag $IMAGE_ID $(imageName2):latest

                echo "Image built and pushed: $(imageName1):$(tag), $(gitsha), latest"
            # Push to second ACR
          - task: AzureCLI@2
            displayName: 'Push to Second ACR'
            inputs:
              azureSubscription: $(azureSubscription2)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name $(acrName2)
                docker push $(imageName2):$(tag)
                docker push $(imageName2):$(gitsha)
                docker push $(imageName2):latest
                echo "Image also pushed to $(imageName2):$(tag), $(gitsha), latest"
